# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lnx/program_study/little_project/GhostEscape_lnx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lnx/program_study/little_project/GhostEscape_lnx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lnx/program_study/little_project/GhostEscape_lnx/CMakeFiles /home/lnx/program_study/little_project/GhostEscape_lnx//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lnx/program_study/little_project/GhostEscape_lnx/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GhostEscape-Linux

# Build rule for target.
GhostEscape-Linux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GhostEscape-Linux
.PHONY : GhostEscape-Linux

# fast build rule for target.
GhostEscape-Linux/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/build
.PHONY : GhostEscape-Linux/fast

src/affiliate/affiliate_bar.o: src/affiliate/affiliate_bar.cpp.o
.PHONY : src/affiliate/affiliate_bar.o

# target to build an object file
src/affiliate/affiliate_bar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/affiliate_bar.cpp.o
.PHONY : src/affiliate/affiliate_bar.cpp.o

src/affiliate/affiliate_bar.i: src/affiliate/affiliate_bar.cpp.i
.PHONY : src/affiliate/affiliate_bar.i

# target to preprocess a source file
src/affiliate/affiliate_bar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/affiliate_bar.cpp.i
.PHONY : src/affiliate/affiliate_bar.cpp.i

src/affiliate/affiliate_bar.s: src/affiliate/affiliate_bar.cpp.s
.PHONY : src/affiliate/affiliate_bar.s

# target to generate assembly for a file
src/affiliate/affiliate_bar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/affiliate_bar.cpp.s
.PHONY : src/affiliate/affiliate_bar.cpp.s

src/affiliate/collider.o: src/affiliate/collider.cpp.o
.PHONY : src/affiliate/collider.o

# target to build an object file
src/affiliate/collider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/collider.cpp.o
.PHONY : src/affiliate/collider.cpp.o

src/affiliate/collider.i: src/affiliate/collider.cpp.i
.PHONY : src/affiliate/collider.i

# target to preprocess a source file
src/affiliate/collider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/collider.cpp.i
.PHONY : src/affiliate/collider.cpp.i

src/affiliate/collider.s: src/affiliate/collider.cpp.s
.PHONY : src/affiliate/collider.s

# target to generate assembly for a file
src/affiliate/collider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/collider.cpp.s
.PHONY : src/affiliate/collider.cpp.s

src/affiliate/sprite.o: src/affiliate/sprite.cpp.o
.PHONY : src/affiliate/sprite.o

# target to build an object file
src/affiliate/sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/sprite.cpp.o
.PHONY : src/affiliate/sprite.cpp.o

src/affiliate/sprite.i: src/affiliate/sprite.cpp.i
.PHONY : src/affiliate/sprite.i

# target to preprocess a source file
src/affiliate/sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/sprite.cpp.i
.PHONY : src/affiliate/sprite.cpp.i

src/affiliate/sprite.s: src/affiliate/sprite.cpp.s
.PHONY : src/affiliate/sprite.s

# target to generate assembly for a file
src/affiliate/sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/sprite.cpp.s
.PHONY : src/affiliate/sprite.cpp.s

src/affiliate/sprite_anim.o: src/affiliate/sprite_anim.cpp.o
.PHONY : src/affiliate/sprite_anim.o

# target to build an object file
src/affiliate/sprite_anim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/sprite_anim.cpp.o
.PHONY : src/affiliate/sprite_anim.cpp.o

src/affiliate/sprite_anim.i: src/affiliate/sprite_anim.cpp.i
.PHONY : src/affiliate/sprite_anim.i

# target to preprocess a source file
src/affiliate/sprite_anim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/sprite_anim.cpp.i
.PHONY : src/affiliate/sprite_anim.cpp.i

src/affiliate/sprite_anim.s: src/affiliate/sprite_anim.cpp.s
.PHONY : src/affiliate/sprite_anim.s

# target to generate assembly for a file
src/affiliate/sprite_anim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/sprite_anim.cpp.s
.PHONY : src/affiliate/sprite_anim.cpp.s

src/affiliate/text_label.o: src/affiliate/text_label.cpp.o
.PHONY : src/affiliate/text_label.o

# target to build an object file
src/affiliate/text_label.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/text_label.cpp.o
.PHONY : src/affiliate/text_label.cpp.o

src/affiliate/text_label.i: src/affiliate/text_label.cpp.i
.PHONY : src/affiliate/text_label.i

# target to preprocess a source file
src/affiliate/text_label.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/text_label.cpp.i
.PHONY : src/affiliate/text_label.cpp.i

src/affiliate/text_label.s: src/affiliate/text_label.cpp.s
.PHONY : src/affiliate/text_label.s

# target to generate assembly for a file
src/affiliate/text_label.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/affiliate/text_label.cpp.s
.PHONY : src/affiliate/text_label.cpp.s

src/core/actor.o: src/core/actor.cpp.o
.PHONY : src/core/actor.o

# target to build an object file
src/core/actor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/actor.cpp.o
.PHONY : src/core/actor.cpp.o

src/core/actor.i: src/core/actor.cpp.i
.PHONY : src/core/actor.i

# target to preprocess a source file
src/core/actor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/actor.cpp.i
.PHONY : src/core/actor.cpp.i

src/core/actor.s: src/core/actor.cpp.s
.PHONY : src/core/actor.s

# target to generate assembly for a file
src/core/actor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/actor.cpp.s
.PHONY : src/core/actor.cpp.s

src/core/asset_store.o: src/core/asset_store.cpp.o
.PHONY : src/core/asset_store.o

# target to build an object file
src/core/asset_store.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/asset_store.cpp.o
.PHONY : src/core/asset_store.cpp.o

src/core/asset_store.i: src/core/asset_store.cpp.i
.PHONY : src/core/asset_store.i

# target to preprocess a source file
src/core/asset_store.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/asset_store.cpp.i
.PHONY : src/core/asset_store.cpp.i

src/core/asset_store.s: src/core/asset_store.cpp.s
.PHONY : src/core/asset_store.s

# target to generate assembly for a file
src/core/asset_store.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/asset_store.cpp.s
.PHONY : src/core/asset_store.cpp.s

src/core/game.o: src/core/game.cpp.o
.PHONY : src/core/game.o

# target to build an object file
src/core/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/game.cpp.o
.PHONY : src/core/game.cpp.o

src/core/game.i: src/core/game.cpp.i
.PHONY : src/core/game.i

# target to preprocess a source file
src/core/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/game.cpp.i
.PHONY : src/core/game.cpp.i

src/core/game.s: src/core/game.cpp.s
.PHONY : src/core/game.s

# target to generate assembly for a file
src/core/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/game.cpp.s
.PHONY : src/core/game.cpp.s

src/core/object.o: src/core/object.cpp.o
.PHONY : src/core/object.o

# target to build an object file
src/core/object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/object.cpp.o
.PHONY : src/core/object.cpp.o

src/core/object.i: src/core/object.cpp.i
.PHONY : src/core/object.i

# target to preprocess a source file
src/core/object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/object.cpp.i
.PHONY : src/core/object.cpp.i

src/core/object.s: src/core/object.cpp.s
.PHONY : src/core/object.s

# target to generate assembly for a file
src/core/object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/object.cpp.s
.PHONY : src/core/object.cpp.s

src/core/object_affiliate.o: src/core/object_affiliate.cpp.o
.PHONY : src/core/object_affiliate.o

# target to build an object file
src/core/object_affiliate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/object_affiliate.cpp.o
.PHONY : src/core/object_affiliate.cpp.o

src/core/object_affiliate.i: src/core/object_affiliate.cpp.i
.PHONY : src/core/object_affiliate.i

# target to preprocess a source file
src/core/object_affiliate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/object_affiliate.cpp.i
.PHONY : src/core/object_affiliate.cpp.i

src/core/object_affiliate.s: src/core/object_affiliate.cpp.s
.PHONY : src/core/object_affiliate.s

# target to generate assembly for a file
src/core/object_affiliate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/object_affiliate.cpp.s
.PHONY : src/core/object_affiliate.cpp.s

src/core/object_world.o: src/core/object_world.cpp.o
.PHONY : src/core/object_world.o

# target to build an object file
src/core/object_world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/object_world.cpp.o
.PHONY : src/core/object_world.cpp.o

src/core/object_world.i: src/core/object_world.cpp.i
.PHONY : src/core/object_world.i

# target to preprocess a source file
src/core/object_world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/object_world.cpp.i
.PHONY : src/core/object_world.cpp.i

src/core/object_world.s: src/core/object_world.cpp.s
.PHONY : src/core/object_world.s

# target to generate assembly for a file
src/core/object_world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/object_world.cpp.s
.PHONY : src/core/object_world.cpp.s

src/core/scene.o: src/core/scene.cpp.o
.PHONY : src/core/scene.o

# target to build an object file
src/core/scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/scene.cpp.o
.PHONY : src/core/scene.cpp.o

src/core/scene.i: src/core/scene.cpp.i
.PHONY : src/core/scene.i

# target to preprocess a source file
src/core/scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/scene.cpp.i
.PHONY : src/core/scene.cpp.i

src/core/scene.s: src/core/scene.cpp.s
.PHONY : src/core/scene.s

# target to generate assembly for a file
src/core/scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/core/scene.cpp.s
.PHONY : src/core/scene.cpp.s

src/enemy.o: src/enemy.cpp.o
.PHONY : src/enemy.o

# target to build an object file
src/enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/enemy.cpp.o
.PHONY : src/enemy.cpp.o

src/enemy.i: src/enemy.cpp.i
.PHONY : src/enemy.i

# target to preprocess a source file
src/enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/enemy.cpp.i
.PHONY : src/enemy.cpp.i

src/enemy.s: src/enemy.cpp.s
.PHONY : src/enemy.s

# target to generate assembly for a file
src/enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/enemy.cpp.s
.PHONY : src/enemy.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/player.o: src/player.cpp.o
.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/raw/bg_star.o: src/raw/bg_star.cpp.o
.PHONY : src/raw/bg_star.o

# target to build an object file
src/raw/bg_star.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/raw/bg_star.cpp.o
.PHONY : src/raw/bg_star.cpp.o

src/raw/bg_star.i: src/raw/bg_star.cpp.i
.PHONY : src/raw/bg_star.i

# target to preprocess a source file
src/raw/bg_star.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/raw/bg_star.cpp.i
.PHONY : src/raw/bg_star.cpp.i

src/raw/bg_star.s: src/raw/bg_star.cpp.s
.PHONY : src/raw/bg_star.s

# target to generate assembly for a file
src/raw/bg_star.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/raw/bg_star.cpp.s
.PHONY : src/raw/bg_star.cpp.s

src/raw/stats.o: src/raw/stats.cpp.o
.PHONY : src/raw/stats.o

# target to build an object file
src/raw/stats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/raw/stats.cpp.o
.PHONY : src/raw/stats.cpp.o

src/raw/stats.i: src/raw/stats.cpp.i
.PHONY : src/raw/stats.i

# target to preprocess a source file
src/raw/stats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/raw/stats.cpp.i
.PHONY : src/raw/stats.cpp.i

src/raw/stats.s: src/raw/stats.cpp.s
.PHONY : src/raw/stats.s

# target to generate assembly for a file
src/raw/stats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/raw/stats.cpp.s
.PHONY : src/raw/stats.cpp.s

src/raw/timer.o: src/raw/timer.cpp.o
.PHONY : src/raw/timer.o

# target to build an object file
src/raw/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/raw/timer.cpp.o
.PHONY : src/raw/timer.cpp.o

src/raw/timer.i: src/raw/timer.cpp.i
.PHONY : src/raw/timer.i

# target to preprocess a source file
src/raw/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/raw/timer.cpp.i
.PHONY : src/raw/timer.cpp.i

src/raw/timer.s: src/raw/timer.cpp.s
.PHONY : src/raw/timer.s

# target to generate assembly for a file
src/raw/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/raw/timer.cpp.s
.PHONY : src/raw/timer.cpp.s

src/raw/weapon.o: src/raw/weapon.cpp.o
.PHONY : src/raw/weapon.o

# target to build an object file
src/raw/weapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/raw/weapon.cpp.o
.PHONY : src/raw/weapon.cpp.o

src/raw/weapon.i: src/raw/weapon.cpp.i
.PHONY : src/raw/weapon.i

# target to preprocess a source file
src/raw/weapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/raw/weapon.cpp.i
.PHONY : src/raw/weapon.cpp.i

src/raw/weapon.s: src/raw/weapon.cpp.s
.PHONY : src/raw/weapon.s

# target to generate assembly for a file
src/raw/weapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/raw/weapon.cpp.s
.PHONY : src/raw/weapon.cpp.s

src/scene_main.o: src/scene_main.cpp.o
.PHONY : src/scene_main.o

# target to build an object file
src/scene_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/scene_main.cpp.o
.PHONY : src/scene_main.cpp.o

src/scene_main.i: src/scene_main.cpp.i
.PHONY : src/scene_main.i

# target to preprocess a source file
src/scene_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/scene_main.cpp.i
.PHONY : src/scene_main.cpp.i

src/scene_main.s: src/scene_main.cpp.s
.PHONY : src/scene_main.s

# target to generate assembly for a file
src/scene_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/scene_main.cpp.s
.PHONY : src/scene_main.cpp.s

src/scene_title.o: src/scene_title.cpp.o
.PHONY : src/scene_title.o

# target to build an object file
src/scene_title.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/scene_title.cpp.o
.PHONY : src/scene_title.cpp.o

src/scene_title.i: src/scene_title.cpp.i
.PHONY : src/scene_title.i

# target to preprocess a source file
src/scene_title.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/scene_title.cpp.i
.PHONY : src/scene_title.cpp.i

src/scene_title.s: src/scene_title.cpp.s
.PHONY : src/scene_title.s

# target to generate assembly for a file
src/scene_title.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/scene_title.cpp.s
.PHONY : src/scene_title.cpp.s

src/screen/hud_button.o: src/screen/hud_button.cpp.o
.PHONY : src/screen/hud_button.o

# target to build an object file
src/screen/hud_button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/hud_button.cpp.o
.PHONY : src/screen/hud_button.cpp.o

src/screen/hud_button.i: src/screen/hud_button.cpp.i
.PHONY : src/screen/hud_button.i

# target to preprocess a source file
src/screen/hud_button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/hud_button.cpp.i
.PHONY : src/screen/hud_button.cpp.i

src/screen/hud_button.s: src/screen/hud_button.cpp.s
.PHONY : src/screen/hud_button.s

# target to generate assembly for a file
src/screen/hud_button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/hud_button.cpp.s
.PHONY : src/screen/hud_button.cpp.s

src/screen/hud_skill.o: src/screen/hud_skill.cpp.o
.PHONY : src/screen/hud_skill.o

# target to build an object file
src/screen/hud_skill.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/hud_skill.cpp.o
.PHONY : src/screen/hud_skill.cpp.o

src/screen/hud_skill.i: src/screen/hud_skill.cpp.i
.PHONY : src/screen/hud_skill.i

# target to preprocess a source file
src/screen/hud_skill.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/hud_skill.cpp.i
.PHONY : src/screen/hud_skill.cpp.i

src/screen/hud_skill.s: src/screen/hud_skill.cpp.s
.PHONY : src/screen/hud_skill.s

# target to generate assembly for a file
src/screen/hud_skill.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/hud_skill.cpp.s
.PHONY : src/screen/hud_skill.cpp.s

src/screen/hud_stats.o: src/screen/hud_stats.cpp.o
.PHONY : src/screen/hud_stats.o

# target to build an object file
src/screen/hud_stats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/hud_stats.cpp.o
.PHONY : src/screen/hud_stats.cpp.o

src/screen/hud_stats.i: src/screen/hud_stats.cpp.i
.PHONY : src/screen/hud_stats.i

# target to preprocess a source file
src/screen/hud_stats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/hud_stats.cpp.i
.PHONY : src/screen/hud_stats.cpp.i

src/screen/hud_stats.s: src/screen/hud_stats.cpp.s
.PHONY : src/screen/hud_stats.s

# target to generate assembly for a file
src/screen/hud_stats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/hud_stats.cpp.s
.PHONY : src/screen/hud_stats.cpp.s

src/screen/hud_text.o: src/screen/hud_text.cpp.o
.PHONY : src/screen/hud_text.o

# target to build an object file
src/screen/hud_text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/hud_text.cpp.o
.PHONY : src/screen/hud_text.cpp.o

src/screen/hud_text.i: src/screen/hud_text.cpp.i
.PHONY : src/screen/hud_text.i

# target to preprocess a source file
src/screen/hud_text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/hud_text.cpp.i
.PHONY : src/screen/hud_text.cpp.i

src/screen/hud_text.s: src/screen/hud_text.cpp.s
.PHONY : src/screen/hud_text.s

# target to generate assembly for a file
src/screen/hud_text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/hud_text.cpp.s
.PHONY : src/screen/hud_text.cpp.s

src/screen/ui_mouse.o: src/screen/ui_mouse.cpp.o
.PHONY : src/screen/ui_mouse.o

# target to build an object file
src/screen/ui_mouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/ui_mouse.cpp.o
.PHONY : src/screen/ui_mouse.cpp.o

src/screen/ui_mouse.i: src/screen/ui_mouse.cpp.i
.PHONY : src/screen/ui_mouse.i

# target to preprocess a source file
src/screen/ui_mouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/ui_mouse.cpp.i
.PHONY : src/screen/ui_mouse.cpp.i

src/screen/ui_mouse.s: src/screen/ui_mouse.cpp.s
.PHONY : src/screen/ui_mouse.s

# target to generate assembly for a file
src/screen/ui_mouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/screen/ui_mouse.cpp.s
.PHONY : src/screen/ui_mouse.cpp.s

src/spawner.o: src/spawner.cpp.o
.PHONY : src/spawner.o

# target to build an object file
src/spawner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/spawner.cpp.o
.PHONY : src/spawner.cpp.o

src/spawner.i: src/spawner.cpp.i
.PHONY : src/spawner.i

# target to preprocess a source file
src/spawner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/spawner.cpp.i
.PHONY : src/spawner.cpp.i

src/spawner.s: src/spawner.cpp.s
.PHONY : src/spawner.s

# target to generate assembly for a file
src/spawner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/spawner.cpp.s
.PHONY : src/spawner.cpp.s

src/weapon_thunder.o: src/weapon_thunder.cpp.o
.PHONY : src/weapon_thunder.o

# target to build an object file
src/weapon_thunder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/weapon_thunder.cpp.o
.PHONY : src/weapon_thunder.cpp.o

src/weapon_thunder.i: src/weapon_thunder.cpp.i
.PHONY : src/weapon_thunder.i

# target to preprocess a source file
src/weapon_thunder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/weapon_thunder.cpp.i
.PHONY : src/weapon_thunder.cpp.i

src/weapon_thunder.s: src/weapon_thunder.cpp.s
.PHONY : src/weapon_thunder.s

# target to generate assembly for a file
src/weapon_thunder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/weapon_thunder.cpp.s
.PHONY : src/weapon_thunder.cpp.s

src/world/effect.o: src/world/effect.cpp.o
.PHONY : src/world/effect.o

# target to build an object file
src/world/effect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/world/effect.cpp.o
.PHONY : src/world/effect.cpp.o

src/world/effect.i: src/world/effect.cpp.i
.PHONY : src/world/effect.i

# target to preprocess a source file
src/world/effect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/world/effect.cpp.i
.PHONY : src/world/effect.cpp.i

src/world/effect.s: src/world/effect.cpp.s
.PHONY : src/world/effect.s

# target to generate assembly for a file
src/world/effect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/world/effect.cpp.s
.PHONY : src/world/effect.cpp.s

src/world/spell.o: src/world/spell.cpp.o
.PHONY : src/world/spell.o

# target to build an object file
src/world/spell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/world/spell.cpp.o
.PHONY : src/world/spell.cpp.o

src/world/spell.i: src/world/spell.cpp.i
.PHONY : src/world/spell.i

# target to preprocess a source file
src/world/spell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/world/spell.cpp.i
.PHONY : src/world/spell.cpp.i

src/world/spell.s: src/world/spell.cpp.s
.PHONY : src/world/spell.s

# target to generate assembly for a file
src/world/spell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GhostEscape-Linux.dir/build.make CMakeFiles/GhostEscape-Linux.dir/src/world/spell.cpp.s
.PHONY : src/world/spell.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GhostEscape-Linux"
	@echo "... src/affiliate/affiliate_bar.o"
	@echo "... src/affiliate/affiliate_bar.i"
	@echo "... src/affiliate/affiliate_bar.s"
	@echo "... src/affiliate/collider.o"
	@echo "... src/affiliate/collider.i"
	@echo "... src/affiliate/collider.s"
	@echo "... src/affiliate/sprite.o"
	@echo "... src/affiliate/sprite.i"
	@echo "... src/affiliate/sprite.s"
	@echo "... src/affiliate/sprite_anim.o"
	@echo "... src/affiliate/sprite_anim.i"
	@echo "... src/affiliate/sprite_anim.s"
	@echo "... src/affiliate/text_label.o"
	@echo "... src/affiliate/text_label.i"
	@echo "... src/affiliate/text_label.s"
	@echo "... src/core/actor.o"
	@echo "... src/core/actor.i"
	@echo "... src/core/actor.s"
	@echo "... src/core/asset_store.o"
	@echo "... src/core/asset_store.i"
	@echo "... src/core/asset_store.s"
	@echo "... src/core/game.o"
	@echo "... src/core/game.i"
	@echo "... src/core/game.s"
	@echo "... src/core/object.o"
	@echo "... src/core/object.i"
	@echo "... src/core/object.s"
	@echo "... src/core/object_affiliate.o"
	@echo "... src/core/object_affiliate.i"
	@echo "... src/core/object_affiliate.s"
	@echo "... src/core/object_world.o"
	@echo "... src/core/object_world.i"
	@echo "... src/core/object_world.s"
	@echo "... src/core/scene.o"
	@echo "... src/core/scene.i"
	@echo "... src/core/scene.s"
	@echo "... src/enemy.o"
	@echo "... src/enemy.i"
	@echo "... src/enemy.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/raw/bg_star.o"
	@echo "... src/raw/bg_star.i"
	@echo "... src/raw/bg_star.s"
	@echo "... src/raw/stats.o"
	@echo "... src/raw/stats.i"
	@echo "... src/raw/stats.s"
	@echo "... src/raw/timer.o"
	@echo "... src/raw/timer.i"
	@echo "... src/raw/timer.s"
	@echo "... src/raw/weapon.o"
	@echo "... src/raw/weapon.i"
	@echo "... src/raw/weapon.s"
	@echo "... src/scene_main.o"
	@echo "... src/scene_main.i"
	@echo "... src/scene_main.s"
	@echo "... src/scene_title.o"
	@echo "... src/scene_title.i"
	@echo "... src/scene_title.s"
	@echo "... src/screen/hud_button.o"
	@echo "... src/screen/hud_button.i"
	@echo "... src/screen/hud_button.s"
	@echo "... src/screen/hud_skill.o"
	@echo "... src/screen/hud_skill.i"
	@echo "... src/screen/hud_skill.s"
	@echo "... src/screen/hud_stats.o"
	@echo "... src/screen/hud_stats.i"
	@echo "... src/screen/hud_stats.s"
	@echo "... src/screen/hud_text.o"
	@echo "... src/screen/hud_text.i"
	@echo "... src/screen/hud_text.s"
	@echo "... src/screen/ui_mouse.o"
	@echo "... src/screen/ui_mouse.i"
	@echo "... src/screen/ui_mouse.s"
	@echo "... src/spawner.o"
	@echo "... src/spawner.i"
	@echo "... src/spawner.s"
	@echo "... src/weapon_thunder.o"
	@echo "... src/weapon_thunder.i"
	@echo "... src/weapon_thunder.s"
	@echo "... src/world/effect.o"
	@echo "... src/world/effect.i"
	@echo "... src/world/effect.s"
	@echo "... src/world/spell.o"
	@echo "... src/world/spell.i"
	@echo "... src/world/spell.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

